#import "../fragments/OrganizationBasic.gql"

query GetUserDefaultOrganization($userId: String!) {
  organization_roles(
    where: {
      user_id: { _eq: $userId }
      is_default_org: { _eq: true }
      is_active: { _eq: true }
    }
    limit: 1
  ) {
    id
    is_default_org
    organization {
      ...OrganizationBasic
    }
    role {
      id
      unique_name
      name
      can_manage_forms
      can_manage_testimonials
      can_manage_widgets
      can_manage_members
      can_manage_billing
      can_delete_org
      is_viewer
    }
  }
}
