#import "../fragments/FormBasic.gql"

query GetForms($organizationId: String!) {
  forms(
    where: { organization_id: { _eq: $organizationId }, is_active: { _eq: true } }
    order_by: { created_at: desc }
  ) {
    ...FormBasic
  }
}
