/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[org]/': RouteRecordInfo<'/[org]/', '/:org', { org: ParamValue<true> }, { org: ParamValue<false> }>,
    '/[org]/dashboard': RouteRecordInfo<'/[org]/dashboard', '/:org/dashboard', { org: ParamValue<true> }, { org: ParamValue<false> }>,
    '/[org]/forms/': RouteRecordInfo<'/[org]/forms/', '/:org/forms', { org: ParamValue<true> }, { org: ParamValue<false> }>,
    '/[org]/forms/[urlSlug]/': RouteRecordInfo<'/[org]/forms/[urlSlug]/', '/:org/forms/:urlSlug', { org: ParamValue<true>, urlSlug: ParamValue<true> }, { org: ParamValue<false>, urlSlug: ParamValue<false> }>,
    '/[org]/forms/[urlSlug]/analytics': RouteRecordInfo<'/[org]/forms/[urlSlug]/analytics', '/:org/forms/:urlSlug/analytics', { org: ParamValue<true>, urlSlug: ParamValue<true> }, { org: ParamValue<false>, urlSlug: ParamValue<false> }>,
    '/[org]/forms/[urlSlug]/responses': RouteRecordInfo<'/[org]/forms/[urlSlug]/responses', '/:org/forms/:urlSlug/responses', { org: ParamValue<true>, urlSlug: ParamValue<true> }, { org: ParamValue<false>, urlSlug: ParamValue<false> }>,
    '/[org]/forms/[urlSlug]/settings': RouteRecordInfo<'/[org]/forms/[urlSlug]/settings', '/:org/forms/:urlSlug/settings', { org: ParamValue<true>, urlSlug: ParamValue<true> }, { org: ParamValue<false>, urlSlug: ParamValue<false> }>,
    '/[org]/forms/[urlSlug]/studio': RouteRecordInfo<'/[org]/forms/[urlSlug]/studio', '/:org/forms/:urlSlug/studio', { org: ParamValue<true>, urlSlug: ParamValue<true> }, { org: ParamValue<false>, urlSlug: ParamValue<false> }>,
    '/[org]/forms/[urlSlug]/testimonials': RouteRecordInfo<'/[org]/forms/[urlSlug]/testimonials', '/:org/forms/:urlSlug/testimonials', { org: ParamValue<true>, urlSlug: ParamValue<true> }, { org: ParamValue<false>, urlSlug: ParamValue<false> }>,
    '/[org]/forms/[urlSlug]/widgets': RouteRecordInfo<'/[org]/forms/[urlSlug]/widgets', '/:org/forms/:urlSlug/widgets', { org: ParamValue<true>, urlSlug: ParamValue<true> }, { org: ParamValue<false>, urlSlug: ParamValue<false> }>,
    '/[org]/forms/creating': RouteRecordInfo<'/[org]/forms/creating', '/:org/forms/creating', { org: ParamValue<true> }, { org: ParamValue<false> }>,
    '/[org]/settings/': RouteRecordInfo<'/[org]/settings/', '/:org/settings', { org: ParamValue<true> }, { org: ParamValue<false> }>,
    '/[org]/settings/billing': RouteRecordInfo<'/[org]/settings/billing', '/:org/settings/billing', { org: ParamValue<true> }, { org: ParamValue<false> }>,
    '/[org]/settings/team': RouteRecordInfo<'/[org]/settings/team', '/:org/settings/team', { org: ParamValue<true> }, { org: ParamValue<false> }>,
    '/[org]/testimonials/': RouteRecordInfo<'/[org]/testimonials/', '/:org/testimonials', { org: ParamValue<true> }, { org: ParamValue<false> }>,
    '/[org]/testimonials/[urlSlug]': RouteRecordInfo<'/[org]/testimonials/[urlSlug]', '/:org/testimonials/:urlSlug', { org: ParamValue<true>, urlSlug: ParamValue<true> }, { org: ParamValue<false>, urlSlug: ParamValue<false> }>,
    '/[org]/widgets/': RouteRecordInfo<'/[org]/widgets/', '/:org/widgets', { org: ParamValue<true> }, { org: ParamValue<false> }>,
    '/[org]/widgets/[urlSlug]': RouteRecordInfo<'/[org]/widgets/[urlSlug]', '/:org/widgets/:urlSlug', { org: ParamValue<true>, urlSlug: ParamValue<true> }, { org: ParamValue<false>, urlSlug: ParamValue<false> }>,
    '/[org]/widgets/new': RouteRecordInfo<'/[org]/widgets/new', '/:org/widgets/new', { org: ParamValue<true> }, { org: ParamValue<false> }>,
    '/auth/callback': RouteRecordInfo<'/auth/callback', '/auth/callback', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/logout': RouteRecordInfo<'/auth/logout', '/auth/logout', Record<never, never>, Record<never, never>>,
    '/auth/signup': RouteRecordInfo<'/auth/signup', '/auth/signup', Record<never, never>, Record<never, never>>,
    '/f/[urlSlug]': RouteRecordInfo<'/f/[urlSlug]', '/f/:urlSlug', { urlSlug: ParamValue<true> }, { urlSlug: ParamValue<false> }>,
    '/showcase': RouteRecordInfo<'/showcase', '/showcase', Record<never, never>, Record<never, never>>,
    '/w/[id]': RouteRecordInfo<'/w/[id]', '/w/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }
}
