query FetchUserRoleInOrg($userId: String!, $organizationId: String!) {
  organization_roles(
    where: {
      user_id: { _eq: $userId }
      organization_id: { _eq: $organizationId }
      is_active: { _eq: true }
    }
    limit: 1
  ) {
    id
    organization_id
    role_id
    is_default_org
    organization {
      id
      name
      slug
    }
    role {
      id
      name
      unique_name
    }
  }
}
