import { executeGraphQLAsAdmin } from '@/shared/libs/hasura';
import {
  // Form operations
  CreateTestFormDocument,
  SoftDeleteTestFormDocument,
  CleanupOldTestFormsDocument,
  // Flow operations
  CreateTestFlowDocument,
  // Step operations
  CreateTestFormStepDocument,
  // Question operations
  CreateTestFormQuestionDocument,
  // Types
  type CreateTestFormMutation,
  type SoftDeleteTestFormMutation,
  type CleanupOldTestFormsMutation,
  type CreateTestFlowMutation,
  type CreateTestFormStepMutation,
  type CreateTestFormQuestionMutation,
} from '@/graphql/generated/operations';
import type { TestQuestion, TestStep, TestFormResult } from './types';
import { QUESTION_TYPE_IDS } from './constants';

/**
 * Form CRUD operations for E2E testing
 *
 * Creates and manages test forms with steps and questions.
 * All operations use admin client to bypass RLS.
 * User/org IDs come from environment variables - no DB lookups needed.
 * IDs are generated by the database using generate_nanoid_12().
 */

/**
 * Create a test form with a flow, steps, and questions
 *
 * Creates a complete form structure suitable for E2E testing:
 * - 1 form with "E2E Test Form" prefix
 * - 1 primary flow
 * - 3 steps: welcome, rating, thank_you
 * - 1 rating question on the rating step
 *
 * IDs are generated by the database (not client-side).
 * Returns full data so tests can use actual values for assertions.
 *
 * @param organizationId - Organization ID (from E2E_ORGANIZATION_ID env var)
 * @param name - Form name (will be prefixed with "E2E Test Form - ")
 * @param createdBy - User ID (from E2E_USER_ID env var)
 * @returns Full form data including steps and questions for test assertions
 */
export async function createTestFormWithSteps(
  organizationId: string,
  name: string,
  createdBy: string
): Promise<TestFormResult> {
  const formName = `E2E Test Form - ${name}`;

  // 1. Create the form (DB generates ID)
  const { data: formData, error: formError } = await executeGraphQLAsAdmin<CreateTestFormMutation>(
    CreateTestFormDocument,
    {
      organization_id: organizationId,
      name: formName,
      status: 'draft',
      created_by: createdBy,
      product_name: 'Test Product',
      product_description: 'A test product for E2E testing',
    }
  );

  if (formError || !formData?.insert_forms_one?.id) {
    throw new Error(`Failed to create test form: ${formError?.message || 'No form ID returned'}`);
  }

  const formId = formData.insert_forms_one.id;

  // 2. Create the primary flow (DB generates ID)
  const { data: flowData, error: flowError } = await executeGraphQLAsAdmin<CreateTestFlowMutation>(
    CreateTestFlowDocument,
    {
      form_id: formId,
      organization_id: organizationId,
      name: 'Main Flow',
      flow_type: 'shared',
      is_primary: true,
      display_order: 0,
    }
  );

  if (flowError || !flowData?.insert_flows_one?.id) {
    throw new Error(`Failed to create test flow: ${flowError?.message || 'No flow ID returned'}`);
  }

  const flowId = flowData.insert_flows_one.id;

  // 3. Create steps (DB generates IDs)
  const stepConfigs = [
    { stepType: 'welcome' as const, stepOrder: 0 },
    { stepType: 'rating' as const, stepOrder: 1 },
    { stepType: 'thank_you' as const, stepOrder: 2 },
  ];

  const steps: TestStep[] = [];

  for (const config of stepConfigs) {
    const { data: stepData, error: stepError } = await executeGraphQLAsAdmin<CreateTestFormStepMutation>(
      CreateTestFormStepDocument,
      {
        flow_id: flowId,
        organization_id: organizationId,
        step_type: config.stepType,
        step_order: config.stepOrder,
        is_active: true,
      }
    );

    if (stepError || !stepData?.insert_form_steps_one?.id) {
      throw new Error(`Failed to create test step: ${stepError?.message || 'No step ID returned'}`);
    }

    const stepId = stepData.insert_form_steps_one.id;
    const questions: TestQuestion[] = [];

    // Add rating question to rating step
    if (config.stepType === 'rating') {
      const questionText = 'How would you rate your experience?';
      const questionKey = 'experience_rating';

      const { data: questionData, error: questionError } = await executeGraphQLAsAdmin<CreateTestFormQuestionMutation>(
        CreateTestFormQuestionDocument,
        {
          step_id: stepId,
          organization_id: organizationId,
          question_type_id: QUESTION_TYPE_IDS.RATING_STAR,
          question_text: questionText,
          question_key: questionKey,
          display_order: 1,
          is_required: true,
          is_active: true,
        }
      );

      if (questionError || !questionData?.insert_form_questions_one?.id) {
        throw new Error(`Failed to create test question: ${questionError?.message || 'No question ID returned'}`);
      }

      questions.push({
        id: questionData.insert_form_questions_one.id,
        stepId,
        questionText,
        questionKey,
        questionTypeId: QUESTION_TYPE_IDS.RATING_STAR,
        displayOrder: 1,
        isRequired: true,
      });
    }

    steps.push({
      id: stepId,
      stepType: config.stepType,
      stepOrder: config.stepOrder,
      questions,
    });
  }

  return {
    formId,
    formName,
    flowId,
    steps,
  };
}

/**
 * Soft delete a test form by setting is_active to false
 *
 * @param formId - Form ID to soft delete
 * @returns true if form was deleted, false otherwise
 */
export async function deleteTestForm(formId: string): Promise<boolean> {
  const { data, error } = await executeGraphQLAsAdmin<SoftDeleteTestFormMutation>(
    SoftDeleteTestFormDocument,
    { id: formId }
  );

  if (error) {
    console.error('Error deleting test form:', error);
    return false;
  }

  return data?.update_forms_by_pk !== null && data?.update_forms_by_pk?.is_active === false;
}

/**
 * Clean up old E2E test data by soft-deleting forms older than specified hours
 *
 * Only affects forms with names starting with "E2E Test Form"
 *
 * @param organizationId - Organization ID to clean up
 * @param olderThanHours - Delete forms older than this many hours (default: 24)
 * @returns Number of forms soft-deleted
 */
export async function cleanupTestData(
  organizationId: string,
  olderThanHours: number = 24
): Promise<number> {
  const cutoffTime = new Date(Date.now() - olderThanHours * 60 * 60 * 1000).toISOString();

  const { data, error } = await executeGraphQLAsAdmin<CleanupOldTestFormsMutation>(
    CleanupOldTestFormsDocument,
    {
      organization_id: organizationId,
      cutoff_time: cutoffTime,
    }
  );

  if (error) {
    console.error('Error cleaning up test data:', error);
    return 0;
  }

  return data?.update_forms?.affected_rows ?? 0;
}
