#import "./FormQuestionBasic.gql"
#import "../../../questionOption/graphql/fragments/QuestionOptionBasic.gql"

fragment FormQuestionWithOptions on form_questions {
  ...FormQuestionBasic
  scale_min_label
  scale_max_label
  options(order_by: { display_order: asc }, where: { is_active: { _eq: true } }) {
    ...QuestionOptionBasic
  }
}
