import { executeGraphQLAsAdmin } from '@/shared/libs/hasura';
import {
  CreateTestFormDocument,
  CreateTestFlowDocument,
  CreateTestFormStepDocument,
  CreateTestFormQuestionDocument,
  type CreateTestFormMutation,
  type CreateTestFlowMutation,
  type CreateTestFormStepMutation,
  type CreateTestFormQuestionMutation,
} from '@/graphql/generated/operations';
import type { TestQuestion, TestStep, TestFormResult } from '../types';
import { QUESTION_TYPE_IDS } from '../constants';

/**
 * Create a test form with a flow, steps, and questions
 *
 * Creates a complete form structure suitable for E2E testing:
 * - 1 form with "E2E Test Form" prefix
 * - 1 primary flow
 * - 5 steps with different types for comprehensive testing:
 *   - welcome (step_order: 0) - intro screen
 *   - question (step_order: 1) - text input with long text question
 *   - rating (step_order: 2) - star rating question
 *   - contact_info (step_order: 3) - submitter details
 *   - thank_you (step_order: 4) - completion screen
 *
 * IDs are generated by the database (not client-side).
 * Returns full data so tests can use actual values for assertions.
 *
 * @param organizationId - Organization ID (from E2E_ORGANIZATION_ID env var)
 * @param name - Form name (will be prefixed with "E2E Test Form - ")
 * @param createdBy - User ID (from E2E_USER_ID env var)
 * @returns Full form data including steps and questions for test assertions
 */
export async function createTestFormWithSteps(
  organizationId: string,
  name: string,
  createdBy: string
): Promise<TestFormResult> {
  const formName = `E2E Test Form - ${name}`;

  // 1. Create the form (DB generates ID)
  const { data: formData, error: formError } = await executeGraphQLAsAdmin<CreateTestFormMutation>(
    CreateTestFormDocument,
    {
      organization_id: organizationId,
      name: formName,
      status: 'draft',
      created_by: createdBy,
      product_name: 'Test Product',
      product_description: 'A test product for E2E testing',
    }
  );

  if (formError || !formData?.insert_forms_one?.id) {
    throw new Error(`Failed to create test form: ${formError?.message || 'No form ID returned'}`);
  }

  const formId = formData.insert_forms_one.id;

  // 2. Create the primary flow (DB generates ID)
  const { data: flowData, error: flowError } = await executeGraphQLAsAdmin<CreateTestFlowMutation>(
    CreateTestFlowDocument,
    {
      form_id: formId,
      organization_id: organizationId,
      name: 'Main Flow',
      flow_type: 'shared',
      is_primary: true,
      display_order: 0,
    }
  );

  if (flowError || !flowData?.insert_flows_one?.id) {
    throw new Error(`Failed to create test flow: ${flowError?.message || 'No flow ID returned'}`);
  }

  const flowId = flowData.insert_flows_one.id;

  // 3. Create steps (DB generates IDs)
  // 5 steps with different types for comprehensive testing
  const stepConfigs: Array<{
    stepType: TestStep['stepType'];
    stepOrder: number;
    question?: { text: string; key: string; typeId: string };
  }> = [
    { stepType: 'welcome', stepOrder: 0 },
    {
      stepType: 'question',
      stepOrder: 1,
      question: {
        text: 'What challenges did you face before using our product?',
        key: 'challenges',
        typeId: QUESTION_TYPE_IDS.TEXT_LONG,
      },
    },
    {
      stepType: 'rating',
      stepOrder: 2,
      question: {
        text: 'How would you rate your experience?',
        key: 'experience_rating',
        typeId: QUESTION_TYPE_IDS.RATING_STAR,
      },
    },
    { stepType: 'contact_info', stepOrder: 3 },
    { stepType: 'thank_you', stepOrder: 4 },
  ];

  const steps: TestStep[] = [];

  for (const config of stepConfigs) {
    const { data: stepData, error: stepError } = await executeGraphQLAsAdmin<CreateTestFormStepMutation>(
      CreateTestFormStepDocument,
      {
        flow_id: flowId,
        organization_id: organizationId,
        step_type: config.stepType,
        step_order: config.stepOrder,
        is_active: true,
      }
    );

    if (stepError || !stepData?.insert_form_steps_one?.id) {
      throw new Error(`Failed to create test step: ${stepError?.message || 'No step ID returned'}`);
    }

    const stepId = stepData.insert_form_steps_one.id;
    const questions: TestQuestion[] = [];

    // Add question if configured for this step
    if (config.question) {
      const { data: questionData, error: questionError } = await executeGraphQLAsAdmin<CreateTestFormQuestionMutation>(
        CreateTestFormQuestionDocument,
        {
          step_id: stepId,
          organization_id: organizationId,
          question_type_id: config.question.typeId,
          question_text: config.question.text,
          question_key: config.question.key,
          display_order: 1,
          is_required: true,
          is_active: true,
        }
      );

      if (questionError || !questionData?.insert_form_questions_one?.id) {
        throw new Error(`Failed to create test question: ${questionError?.message || 'No question ID returned'}`);
      }

      questions.push({
        id: questionData.insert_form_questions_one.id,
        stepId,
        questionText: config.question.text,
        questionKey: config.question.key,
        questionTypeId: config.question.typeId,
        displayOrder: 1,
        isRequired: true,
      });
    }

    steps.push({
      id: stepId,
      stepType: config.stepType,
      stepOrder: config.stepOrder,
      questions,
    });
  }

  return {
    formId,
    formName,
    flowId,
    steps,
  };
}
