/**
 * Form CRUD operations for E2E testing
 *
 * Creates and manages test forms with steps and questions.
 * All operations use admin client to bypass RLS.
 * User/org IDs come from environment variables - no DB lookups needed.
 * IDs are generated by the database using generate_nanoid_12().
 */

// Simple form creation
export { createTestFormWithSteps } from './createSimpleForm';

// Branched form creation
export { createTestFormWithBranching } from './createBranchedForm';

// Choice question form creation
export { createTestFormWithChoiceQuestion } from './createChoiceQuestionForm';

// Delete and cleanup operations
export { deleteTestForm, cleanupTestData } from './deleteForm';

// Re-export shared primitives for external use
export {
  createStep,
  createQuestion,
  createQuestionOption,
  getQuestionTypeId,
  DEFAULT_STEP_CONTENT,
} from './shared';
