/**
 * Form CRUD operations for E2E testing
 *
 * Creates and manages test forms with steps and questions.
 * All operations use admin client to bypass RLS.
 * User/org IDs come from environment variables - no DB lookups needed.
 * IDs are generated by the database using generate_nanoid_12().
 */

// Simple form creation
export { createTestFormWithSteps } from './create-simple';

// Branched form creation
export { createTestFormWithBranching } from './create-branched';

// Delete and cleanup operations
export { deleteTestForm, cleanupTestData } from './delete';

// Helpers (exported for potential reuse)
export { createStep, createQuestion, DEFAULT_STEP_CONTENT } from './helpers';
