mutation CreateIdentity(
  $user_id: String!
  $provider: String!
  $provider_user_id: String!
  $provider_email: String
  $provider_metadata: jsonb
  $is_primary: Boolean!
) {
  insert_user_identities_one(
    object: {
      user_id: $user_id
      provider: $provider
      provider_user_id: $provider_user_id
      provider_email: $provider_email
      provider_metadata: $provider_metadata
      is_primary: $is_primary
      verified_at: "now()"
    }
  ) {
    id
    user_id
    provider
  }
}
