fragment WidgetBasic on widgets {
  id
  organization_id
  created_by
  name
  type
  theme
  show_ratings
  show_dates
  show_company
  show_avatar
  max_display
  settings
  is_active
  created_at
  updated_at
}
